version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment when you add database support
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: graphql_db
  #     POSTGRES_USER: ${DB_USER:-graphql_user}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-graphql_password}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
#   redis_data:
